---
abstract: 'Simplistic bootstrapping for DBIx::Class'
author:
  - 'Ohio-Pennsylvania Software, LLC.'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Bootstrap-Simple
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  perl: 5.8.4
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
